version: '2.1'

services:

  score-keeper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: ./env/server.env
    depends_on:
      database:
        condition: service_healthy
 
  database:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    volumes:
      - database-data:/var/lib/mysql
      - ./database_init:/docker-entrypoint-initdb.d   
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=github_scoring_service
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    healthcheck:
      test: mysql -e exit
      timeout: 3s
      interval: 5s
      retries: 10

volumes:
  database-data: